Add resort page
dorkka/NartyGo pull request #4
Opened 2018-03-23 16:45 UTC by dorkka

Add hardcoded weather info for resorts to db.json, add SpecificResortPage with details and weather

2018-03-24 07:38 UTC, pokiujf commented on src/components/resortPage/SpecificResortPage.js
> +    fetch(`http://localhost:3001/resorts/${this.state.resortId}`)
note: refactor this to HOC

2018-03-24 07:38 UTC, pokiujf commented on src/components/resortPage/ResortWeatherInfo.js
> +        <p>Temperatura: {this.props.temperature}</p>
note: use destructuring and functional components?

2018-03-24 08:25 UTC, pokiujf commented
Check code auto styling in VSCode

2018-03-24 08:28 UTC, pokiujf commented
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

2018-04-06 08:31 UTC, ar-mac requested changes

2018-04-06 08:31 UTC, ar-mac commented on src/components/ResortsData.js
> +  constructor() {
No need for constructor. Define `state` as class property

2018-04-06 08:31 UTC, pokiujf commented on src/services/resourceFetcher.js
> +export default url => (params) => {
(minor) 
`export default resourceFetcher`

2018-04-06 08:31 UTC, pokiujf commented on src/components/resortPage/SpecificResortPage.js
> +
✂️

2018-04-06 08:35 UTC, pokiujf commented
![](https://github.trello.services/images/mini-trello-icon.png) [Use React-Router for routing instead of home made routing solution](https://trello.com/c/R0ZgsdcQ/17-use-react-router-for-routing-instead-of-home-made-routing-solution)

2018-04-16 06:48 UTC, pokiujf commented on src/components/resortPage/SpecificResortPage.js
> +        let message = 'Something went wrong ...';
- This should be done only in resourceFetcher
- Use Resource fetcher here
- In state set only resort and isLoading

2018-04-19 06:37 UTC, ar-mac approved these changes

2018-04-19 11:15 UTC, merged